/*!
* \file   Ogden.cxx
* \brief  this file implements the Ogden Behaviour.
*         File generated by tfel version 4.0.0-dev
* \author Thomas Helfer
* \date   20 / 12 / 2016
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/OgdenBehaviourData.hxx"
#include"TFEL/Material/OgdenIntegrationData.hxx"
#include"TFEL/Material/Ogden.hxx"

namespace tfel{

namespace material{

OgdenParametersInitializer&
OgdenParametersInitializer::get()
{
static OgdenParametersInitializer i;
return i;
}

OgdenParametersInitializer::OgdenParametersInitializer()
{
this->alpha = 28.8;
this->mu = 27778;
this->K = 69444444;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
// Reading parameters from a file
OgdenParametersInitializer::readParameters(*this,"Ogden-parameters.txt");
}

void
OgdenParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("alpha",key)==0){
this->alpha = v;
} else if(::strcmp("mu",key)==0){
this->mu = v;
} else if(::strcmp("K",key)==0){
this->K = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else {
tfel::raise("OgdenParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

double
OgdenParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"OgdenParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

void
OgdenParametersInitializer::readParameters(OgdenParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"OgdenParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("alpha"==tokens[0]){
pi.alpha = OgdenParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("mu"==tokens[0]){
pi.mu = OgdenParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("K"==tokens[0]){
pi.K = OgdenParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = OgdenParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = OgdenParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace material

} // end of namespace tfel

